---
# tasks file for duf | Debian/Ubuntu Family

- name: Debian/Ubuntu Family | Downloading and installing {{ duf_app }} {{ duf_version }}
  ansible.builtin.apt:
    deb: "{{ duf_debian_url }}"
    state: "{{ duf_desired_state }}"
